config/routes.rb
Rails.application.routes.draw do
  resources :packagings

  resources :units

  get 'landings/index'

  resources :suppliers

  resources :shipping_addresses

  resources :customers

  resources :order_items

  resources :orders

  resources :stocks

  resources :ingredients

  resources :stock_types

  resources :ingredient_instances

  get '/new_customer_order_form', :controller => 'forms', :action => 'new_customer_order_form', :as => 'new_customer_order_form'

  get '/customers/:id/new_order',      :controller => 'forms', :action => 'existing_customer_order_form',    :as => 'existing_customer_order_form'

  get '/todays_production', :controller => 'productions', :action => 'todays_production_index',    :as => 'todays_production_index'

  get '/todays_production/:base_stock_type', :controller => 'productions', :action => 'todays_production',    :as => 'todays_production'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'landings#index'

  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session

    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/controllers/landings_controller.rb
class LandingsController < ApplicationController
  def index
  end
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/views/landings/index.html.erb
<%= link_to "New Order",new_customer_order_form_path,:class => 'btn btn-success btn-lg btn-block' %>
<%= link_to "Orders",orders_path,:class => 'btn btn-success btn-lg btn-block' %>

<%= link_to "New Inventory",new_stock_path,:class => 'btn btn-primary btn-lg btn-block' %>
<%= link_to "Inventory",stocks_path,:class => 'btn btn-primary btn-lg btn-block' %>

<%= link_to "Todays Production",todays_production_index_path,:class => 'btn btn-danger btn-lg btn-block' %>

<%= link_to "Customers",customers_path,:class => 'btn btn-warning btn-lg btn-block' %>