config/routes.rb
Rails.application.routes.draw do
  resources :packagings

  resources :units

  get 'landings/index'

  resources :suppliers

  resources :shipping_addresses

  resources :customers

  resources :order_items

  resources :orders

  resources :stocks

  resources :ingredients

  resources :stock_types

  resources :ingredient_instances

  get '/new_customer_order_form', :controller => 'forms', :action => 'new_customer_order_form', :as => 'new_customer_order_form'

  get '/customers/:id/new_order',      :controller => 'forms', :action => 'existing_customer_order_form',    :as => 'existing_customer_order_form'

  get '/todays_production', :controller => 'productions', :action => 'todays_production_index',    :as => 'todays_production_index'

  get '/todays_production/:base_stock_type', :controller => 'productions', :action => 'todays_production',    :as => 'todays_production'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'landings#index'

  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session

    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :stock_type
  belongs_to :stock_type_component, class_name: "StockType", :foreign_key => "stock_type_component_id"
end


# # the stock_type table
# create_table :stock_type do |t|
#   t.column :name, :string
# end

# # the ingredients association table
# create_table :ingredients do |t|
#   t.column :person_id, :integer
#   t.column :stock_type_component_id, :integer
# end

# class Ingredient < ActiveRecord::Base
#   # don't have to give class_name or foreign_key b/c ActiveRecord reflection works here
#   belongs_to :stock_type

#   # make sure to give class_name and foreign_key b/c ActiveRecord doesn't know what stock_type_component is
#   belongs_to :stock_type_component, :class_name => "StockType", :foreign_key => "stock_type_component_id"
# end

# class Person < ActiveRecord::Base
#   # tell ActiveRecord that a stock_type has_many ingredients or :through won't work
#   has_many :ingredients

#   # create the has_many :through relationship
#   has_many :stock_type_components, :through => :ingredients

# end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.all
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
        format.json { render :show, status: :created, location: @ingredient }
      else
        format.html { render :new }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1
  # PATCH/PUT /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully updated.' }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient.destroy
    respond_to do |format|
      format.html { redirect_to ingredients_url, notice: 'Ingredient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ingredient_params
      params.require(:ingredient).permit(:quantity, :unit, :stock_type_id, :stock_type_component_id)
    end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/_form.html.erb
<%= form_for @ingredient, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :quantity, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :quantity, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  ingredients_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/ingredients/edit.html.erb
<%- model_class = Ingredient -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Ingredient %></h1>
</div>
<%= render :partial => 'form' %>

app/views/ingredients/index.html.erb
<%- model_class = Ingredient -%>
<div class="page-header">
  <h1><%=t '.title', :default => Ingredient %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:quantity) %></th>
      <th><%= model_class.human_attribute_name(:unit) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @ingredients.each do |ingredient| %>
      <tr>
        <td><%= ingredient.id %></td>
        <td><%= ingredient.quantity %></td>
        <td><%= ingredient.unit %></td>
        <td><%=l ingredient.created_at, format: :long %></td>
        <td>
          <%= link_to 'Show', ingredient %>
          <%= link_to 'Edit', edit_ingredient_path(ingredient) %>
          <%= link_to 'Destroy', ingredient, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_ingredient_path,
            :class => 'btn btn-primary' %>

app/views/ingredients/new.html.erb
<%- model_class = Ingredient -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Ingredient %></h1>
</div>
<%= render :partial => 'form' %>

app/views/ingredients/show.html.erb
<%- model_class = Ingredient -%>
<div class="page-header">
  <h1><%=t '.title', :default => Ingredient %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:quantity) %></dt>
      <dd><pre class="prettyprint"><%= @ingredient.quantity %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:unit) %></dt>
      <dd><pre class="prettyprint"><%= @ingredient.unit %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              ingredients_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_ingredient_path(@ingredient), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              ingredient_path(@ingredient),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>