config/routes.rb
Rails.application.routes.draw do
  resources :packagings

  resources :units

  get 'landings/index'

  resources :suppliers

  resources :shipping_addresses

  resources :customers

  resources :order_items

  resources :orders

  resources :stocks

  resources :ingredients

  resources :stock_types

  resources :ingredient_instances

  get '/new_customer_order_form', :controller => 'forms', :action => 'new_customer_order_form', :as => 'new_customer_order_form'

  get '/customers/:id/new_order',      :controller => 'forms', :action => 'existing_customer_order_form',    :as => 'existing_customer_order_form'

  get '/todays_production', :controller => 'productions', :action => 'todays_production_index',    :as => 'todays_production_index'

  get '/todays_production/:base_stock_type', :controller => 'productions', :action => 'todays_production',    :as => 'todays_production'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'landings#index'

  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session

    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/ingredient_instance.rb
class IngredientInstance < ActiveRecord::Base
  belongs_to :stock
  belongs_to :stock_component, class_name: "Stock", :foreign_key => "stock_component_id"
end

app/controllers/ingredient_instances_controller.rb
class IngredientInstancesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_ingredient_instance, only: [:show, :edit, :update, :destroy]

  # GET /ingredient_instances
  # GET /ingredient_instances.json
  def index
    @ingredient_instances = IngredientInstance.all
  end

  # GET /ingredient_instances/1
  # GET /ingredient_instances/1.json
  def show
  end

  # GET /ingredient_instances/new
  def new
    @ingredient_instance = IngredientInstance.new
  end

  # GET /ingredient_instances/1/edit
  def edit
  end

  # POST /ingredient_instances
  # POST /ingredient_instances.json
  def create
    @ingredient_instance = IngredientInstance.new(ingredient_instance_params)

    respond_to do |format|
      if @ingredient_instance.save
        format.html { redirect_to @ingredient_instance, notice: 'Ingredient instance was successfully created.' }
        format.json { render :show, status: :created, location: @ingredient_instance }
      else
        format.html { render :new }
        format.json { render json: @ingredient_instance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredient_instances/1
  # PATCH/PUT /ingredient_instances/1.json
  def update
    respond_to do |format|
      if @ingredient_instance.update(ingredient_instance_params)
        format.html { redirect_to @ingredient_instance, notice: 'Ingredient instance was successfully updated.' }
        format.json { render :show, status: :ok, location: @ingredient_instance }
      else
        format.html { render :edit }
        format.json { render json: @ingredient_instance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredient_instances/1
  # DELETE /ingredient_instances/1.json
  def destroy
    @ingredient_instance.destroy
    respond_to do |format|
      format.html { redirect_to ingredient_instances_url, notice: 'Ingredient instance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient_instance
      @ingredient_instance = IngredientInstance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ingredient_instance_params
      params.require(:ingredient_instance).permit(:quantity, :unit, :stock_id, :stock_component_id)
    end
end

app/helpers/ingredient_instances_helper.rb
module IngredientInstancesHelper
end

app/views/ingredient_instances/_form.html.erb
<%= form_for @ingredient_instance, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :quantity, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :quantity, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :unit, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :unit, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  ingredient_instances_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/ingredient_instances/edit.html.erb
<%- model_class = IngredientInstance -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => IngredientInstance %></h1>
</div>
<%= render :partial => 'form' %>

app/views/ingredient_instances/index.html.erb
<%- model_class = IngredientInstance -%>
<div class="page-header">
  <h1><%=t '.title', :default => IngredientInstance %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:quantity) %></th>
      <th><%= model_class.human_attribute_name(:unit) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @ingredient_instances.each do |ingredient_instance| %>
      <tr>
        <td><%= ingredient_instance.id %></td>
        <td><%= ingredient_instance.quantity %></td>
        <td><%= ingredient_instance.unit %></td>
        <td><%=l ingredient_instance.created_at, format: :long %></td>
        <td>
          <%= link_to 'Show', ingredient_instance %>
          <%= link_to 'Edit', edit_ingredient_instance_path(ingredient_instance) %>
          <%= link_to 'Destroy', ingredient_instance, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_ingredient_instance_path,
            :class => 'btn btn-primary' %>

app/views/ingredient_instances/new.html.erb
<%- model_class = IngredientInstance -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => IngredientInstance %></h1>
</div>
<%= render :partial => 'form' %>

app/views/ingredient_instances/show.html.erb
<%- model_class = IngredientInstance -%>
<div class="page-header">
  <h1><%=t '.title', :default => IngredientInstance %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:quantity) %></dt>
      <dd><pre class="prettyprint"><%= @ingredient_instance.quantity %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:unit) %></dt>
      <dd><pre class="prettyprint"><%= @ingredient_instance.unit %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              ingredient_instances_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_ingredient_instance_path(@ingredient_instance), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              ingredient_instance_path(@ingredient_instance),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>