config/routes.rb
Rails.application.routes.draw do
  resources :packagings

  resources :units

  get 'landings/index'

  resources :suppliers

  resources :shipping_addresses

  resources :customers

  resources :order_items

  resources :orders

  resources :stocks

  resources :ingredients

  resources :stock_types

  resources :ingredient_instances

  get '/new_customer_order_form', :controller => 'forms', :action => 'new_customer_order_form', :as => 'new_customer_order_form'

  get '/customers/:id/new_order',      :controller => 'forms', :action => 'existing_customer_order_form',    :as => 'existing_customer_order_form'

  get '/todays_production', :controller => 'productions', :action => 'todays_production_index',    :as => 'todays_production_index'

  get '/todays_production/:base_stock_type', :controller => 'productions', :action => 'todays_production',    :as => 'todays_production'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'landings#index'

  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session

    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/controllers/stock_types_controller.rb
class StockTypesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_stock_type, only: [:show, :edit, :update, :destroy]


  # GET /stock_types
  # GET /stock_types.json
  def index
    @stock_types = StockType.all
  end

  # GET /stock_types/1
  # GET /stock_types/1.json
  def show
  end

  # GET /stock_types/new
  def new
    @stock_type = StockType.new
  end

  # GET /stock_types/1/edit
  def edit
  end

  # POST /stock_types
  # POST /stock_types.json
  def create
    @stock_type = StockType.new(stock_type_params)
    respond_to do |format|
      if @stock_type.save
        format.html { redirect_to @stock_type, notice: 'Stock type was successfully created.' }
        format.json { render :show, status: :created, location: @stock_type }
      else
        format.html { render :new }
        format.json { render json: @stock_type.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /stock_types/1
  # PATCH/PUT /stock_types/1.json
  def update
    respond_to do |format|
      if @stock_type.update(stock_type_params)
        format.html { redirect_to @stock_type, notice: 'Stock type was successfully updated.' }
        format.json { render :show, status: :ok, location: @stock_type }
      else
        format.html { render :edit }
        format.json { render json: @stock_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stock_types/1
  # DELETE /stock_types/1.json
  def destroy
    @stock_type.destroy
    respond_to do |format|
      format.html { redirect_to stock_types_url, notice: 'Stock type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock_type
      @stock_type = StockType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stock_type_params
      params.require(:stock_type).permit(:name, :unit, :category, :base, :price, :base_stock_type_id, ingredients_attributes: [:id, :quantity, :stock_type_id, :stock_type_component_id, :_destroy])
    end
end

app/helpers/stock_types_helper.rb
module StockTypesHelper
end

app/views/stock_types/_form.html.erb
<%= simple_form_for(@stock_type) do |f| %>
  <%= f.error_notification %>
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Stock Type</h3>
      </div>
      <div class="panel-body">
        <div class="form-inputs">
          <%= f.input :base%>
          <div class="col-sm-6">
            <%= f.input :name, input_html: { id: "name_location"}%>
          </div>
          <div class="col-sm-6">
            <%= f.association :base_stock_type, collection: StockType.where(base: true), label_method: :label %>
          </div>
          <div class="col-sm-12">
            <%= f.input :unit%>
            <%= f.input :category, collection: ([ "Raw Ingredient", "Sub-Assembly", "Packaging","Product"])%>
            <%= f.input :price%>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Ingredients</h3>
      </div>
      <div class="panel-body">
        <div class="form-inputs">
          <div id='ingredients'>
            <%= f.simple_fields_for :ingredients do |ingredient| %>
              <%= render 'ingredient_fields', :f => ingredient %>
            <% end %>
            <div class='links'>
              <%= link_to_add_association 'Add ingredient', f, :ingredients, class: "btn btn-default add-button" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/stock_types/_ingredient_fields.html.erb
<div class="nested-fields">
  <div class="row">
    <div class="col-sm-4">
      <%= f.input :quantity %>
    </div>
    <div class="col-sm-4">
      <%= f.association :stock_type_component, input_html: { class: "stock_type_component_selectpicker", "data-live-search":"true"}, label_method: :label%>
    </div>
    <div class="col-sm-4">
      <%= link_to_remove_association 'Remove Order Item', f, class: "btn btn-default btn form-button dropbutton" %>
    </div>
  </div>
</div>
<script type="text/javascript">

</script>

app/views/stock_types/edit.html.erb
<%- model_class = StockType -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => StockType %></h1>
</div>
<%= render :partial => 'form' %>

app/views/stock_types/index.html.erb
<%- model_class = StockType -%>
<div class="page-header">
  <h1><%=t '.title', :default => StockType %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:unit) %></th>
      <th><%= model_class.human_attribute_name(:packaging) %></th>
      <th><%= model_class.human_attribute_name(:base) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @stock_types.each do |stock_type| %>
      <tr>
        <td><%= stock_type.identification %></td>
        <td><%= stock_type.unit %></td>
        <td><%= stock_type.packaging %></td>
        <td><%= stock_type.base %></td>
        <td>
          <%= link_to 'Show', stock_type %>
          <%= link_to 'Edit', edit_stock_type_path(stock_type) %>
          <%= link_to 'Destroy', stock_type, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_stock_type_path,
            :class => 'btn btn-primary' %>

app/views/stock_types/new.html.erb
<%- model_class = StockType -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => StockType %></h1>
</div>
<%= render :partial => 'form' %>

<script type="text/javascript">

</script>

app/views/stock_types/show.html.erb
<%- model_class = StockType -%>
<div class="page-header">
  <h1><%=t '.title', :default => StockType %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:name) %></dt>
      <dd><pre class="prettyprint"><%= @stock_type.identification %></pre></dd>
  </dl>
    <dl>
  <dt class="label label-default"><%= model_class.human_attribute_name(:unit) %></dt>
      <dd><pre class="prettyprint"><%= @stock_type.unit %></pre></dd>
  </dl>
  <dt class="label label-default"><%= model_class.human_attribute_name(:category) %></dt>
      <dd><pre class="prettyprint"><%= @stock_type.category %></pre></dd>
  </dl>
  <dt class="label label-default"><%= model_class.human_attribute_name(:base) %></dt>
      <dd><pre class="prettyprint"><%= @stock_type.base %></pre></dd>
  </dl>
  <dt class="label label-default"><%= model_class.human_attribute_name(:price) %></dt>
      <dd><pre class="prettyprint"><%= @stock_type.price %></pre></dd>
  </dl>
</div>

  <dt class="label label-default">Ingredients</dt>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Quantity</th>
      <th>Name</th>
      <th>Unit</th>
    </tr>
  </thead>
  <tbody>
    <% @stock_type.ingredients.each do |ingredient| %>
      <tr>
        <td><%= ingredient.quantity %></td>
        <td><%= ingredient.stock_type_component.identification %></td>
        <td><%= ingredient.stock_type_component.unit %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              stock_types_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_stock_type_path(@stock_type), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              stock_type_path(@stock_type),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>